### ISSUE TITLE
No DeepCopy on Collections

### ISSUE THREAD

**Issue by mustii82** [bennyhuo/KotlinDeepCopy#1]
Hi under a DeepCopy my Understandig is that even the members should be deepcopys but in this Code:

```
val speaker = Speaker("Benny Huo", arrayListOf(1, 2, 3, 4))
    val talk = Talk("DataClass in Action", speaker)
    val newTalk = talk.deepCopy()

    talk.speaker.arrayList.removeAt(0)

    println(talk)
    println(newTalk)
```

The list will change on both Objects

**Comment by bennyhuo** [comment]
Yes, you're right. Only `data class` annotated by `@DeepCopy` will be handled with `deepCopy` method.

**Comment by bennyhuo** [comment]
Element type in collections could be any type which may not be designed to be deep copied or even copied. 
Maybe we should seek a way to copy collections with a generic `data class` type.

**Comment by bennyhuo** [comment]
Try the new branch v1.3. Use bunch of reflections to do the collection deep copy.

**Comment by mustii82** [comment]
will the objects inside a collection also be deep copied?

**Comment by bennyhuo** [comment]
> will the objects inside a collection also be deep copied?

If the type of the element is Collection or data class annotated with DeepCopy, it will be deep copied.
