### ISSUE TITLE
想复制一份deepCopy方法 但是报红

### ISSUE THREAD

**Issue by petterEat** [bennyhuo/KotlinDeepCopy#10]
![image](https://user-images.githubusercontent.com/16751387/118092964-58a25c80-b3ff-11eb-800c-d03e0614b3fa.png)

**Comment by petterEat** [comment]
另外jcenter即将关闭 ，作者大大可否迁移

**Comment by bennyhuo** [comment]
你复制的是反射版本的代码，这个依赖 Kotlin 反射库，引一下依赖即可。

**Comment by bennyhuo** [comment]
> 另外jcenter即将关闭 ，作者大大可否迁移

嗯，我尽快迁一下到 mavenCentral

**Comment by bennyhuo** [comment]
已经发布到 Maven Center。GroupId 和 ArtifactId 做了调整，请留意 Readme 的说明。
