### ISSUE TITLE
deepcopy-reflect-1.5.0.pom  Forbidden!

### ISSUE THREAD

**Issue by zhushenwudi** [bennyhuo/KotlinDeepCopy#11]
集成
kapt 'com.bennyhuo.kotlin.apt:deepcopy-compiler:1.5.0'
implementation 'com.bennyhuo.kotlin.reflect:deepcopy-reflect:1.5.0'
sync now 之后
Could not GET 'https://kotlin.bintray.com/kotlinx/com/bennyhuo/kotlin/reflect/deepcopy-reflect/1.5.0/deepcopy-reflect-1.5.0.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

访问网址提示Forbidden!

如果不加 project 仓库，会提示
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.bennyhuo.kotlin.reflect:deepcopy-reflect:1.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/bennyhuo/kotlin/reflect/deepcopy-reflect/1.5.0/deepcopy-reflect-1.5.0.pom
       - https://repo.maven.apache.org/maven2/com/bennyhuo/kotlin/reflect/deepcopy-reflect/1.5.0/deepcopy-reflect-1.5.0.pom
       - https://jcenter.bintray.com/com/bennyhuo/kotlin/reflect/deepcopy-reflect/1.5.0/deepcopy-reflect-1.5.0.pom
       - https://jitpack.io/com/bennyhuo/kotlin/reflect/deepcopy-reflect/1.5.0/deepcopy-reflect-1.5.0.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

找不到库

**Comment by zhushenwudi** [comment]
通过访问 mavencenter 查找，找到了依赖地址，作者可以更新一下 readme
kapt 'com.bennyhuo.kotlin.apt:deepcopy-annotations:1.5.0'
implementation 'com.bennyhuo.kotlin.apt:deepcopy-compiler:1.5.0'
implementation 'com.bennyhuo.kotlin.apt:deepcopy-runtime:1.5.0'

**Comment by bennyhuo** [comment]
我其实是更新了的

--------------原始邮件--------------
发件人："zhushenwudi ***@***.***&gt;;
发送时间：2021年7月7日(星期三) 凌晨0:06
收件人："bennyhuo/KotlinDeepCopy" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [bennyhuo/KotlinDeepCopy] deepcopy-reflect-1.5.0.pom  Forbidden! (#11)
-----------------------------------

 

 
通过访问 mavencenter 查找，找到了依赖地址，作者可以更新一下 readme
 kapt 'com.bennyhuo.kotlin.apt:deepcopy-annotations:1.5.0'
 implementation 'com.bennyhuo.kotlin.apt:deepcopy-compiler:1.5.0'
 implementation 'com.bennyhuo.kotlin.apt:deepcopy-runtime:1.5.0'

**Comment by zhushenwudi** [comment]
哈哈，看到了。可以把 kapt的调整到上面，我们很容易看到一个 how to install 之后就复制了。然后发现不能用就只粘贴了下面的 apt，而忽略了 reflect 和 runtime 的区别。原理性的可以放在最下面说
