### ISSUE TITLE
release包混淆后使用闪退

### ISSUE THREAD

**Issue by mistletoe5215** [bennyhuo/KotlinDeepCopy#12]
霍老师，需要给com.bennyhuo.kotlin.deepcopy.DeepCopy 加个keep～

**Comment by bennyhuo** [comment]
apt 的版本吗？对集合框架的依赖是有点儿反射，不过我准备后面移除掉，应该就不用 keep 了

**Comment by mistletoe5215** [comment]
> apt 的版本吗？对集合框架的依赖是有点儿反射，不过我准备后面移除掉，应该就不用 keep 了
> 
> 

好的，期待新版本^_^
