### ISSUE TITLE
Failed to resolve: com.bennyhuo.kotlin.reflect:deepcopy-reflect:1.5.0

### ISSUE THREAD

**Issue by D10NGYANG** [bennyhuo/KotlinDeepCopy#13]
api("com.bennyhuo.kotlin.reflect:deepcopy-reflect:1.5.0")

Failed to resolve: com.bennyhuo.kotlin.reflect:deepcopy-reflect:1.5.0
Show in Project Structure dialog
Affected Modules: app

**Comment by bennyhuo** [comment]
I forgot to publish reflect artifact to Maven Central after the sunset of jcenter. You may try the snapshot version: 

```
com.bennyhuo.kotlin:deepcopy-reflect:1.5.31.0-SNAPSHOT
```

with the snapshot repo:

```
https://oss.sonatype.org/content/repositories/snapshots/
```
 If you wanna use the reflect lib only, you can also copy the code into your project ,it's pretty simple.

**Comment by D10NGYANG** [comment]
好的，十分感谢
