### ISSUE TITLE
deepcopy.kcp-impl.plugin-ide不工作，intelij里标红

### ISSUE THREAD

**Issue by song3liu** [bennyhuo/KotlinDeepCopy#14]
deepcopy.kcp-impl.plugin-ide，编译完之后。
本地安装了build/distributions目录里的DeepCopy-1.6.10.0-SNAPSHOT.zip

同时，deepcopy.kcp-impl.plugin-kcp publish to maven local
deepcopy.kcp-impl.plugin-gradle publish to maven local

但  deepcopy.kcp-impl.sample 工程里的talk.deepCopy() 仍然飘红！Unresolved reference: deepCopy
![1](https://user-images.githubusercontent.com/94161478/172652041-046c64a8-e13b-4a2b-86cf-911ac00db542.jpg)

**Comment by song3liu** [comment]
插件是安装了的
<img width="729" alt="2" src="https://user-images.githubusercontent.com/94161478/172654068-514e9d8e-7213-40ec-822d-c26277ea0737.png">

**Comment by bennyhuo** [comment]
你得把embeddable发布了才行。看你描述，应该是没有发布。

**Comment by song3liu** [comment]
感谢，可以了。
再请教一下：
1、embeddable里面除了gradle文件，没有源码，它起到了什么作用
2、目前这个DeepCopy-1.6.10.0-SNAPSHOT.zip，对deepcopy.kcp-impl.sample 工程里的talk.deepCopy() 可以起效。为什么对deepcopy.sample.sample-jvm工程里Sample中的talk.deepCopy()不起效果。ide插件DeepCopy-1.6.10.0-SNAPSHOT.zip不是全部代码都会起效吗？

**Comment by song3liu** [comment]
deepcopy.sample.sample-jvm里依旧飘红
<img width="898" alt="4" src="https://user-images.githubusercontent.com/94161478/172662937-f62ef817-3ce5-44c9-96bf-ca8ff818b7f0.png">

**Comment by bennyhuo** [comment]
这都是很有意思的细节，你先自己研究一下看看。
