### ISSUE TITLE
Support builtin data types

### ISSUE THREAD

**Issue by bennyhuo** [bennyhuo/KotlinDeepCopy#2]
Something like `Pair<A,B>`, `Tripple<A,B,C>` and so on.

**Comment by mustii82** [comment]
We should include DeepCopy for every DataType in the Data Class to provide a 100% DeepCopy

**Comment by bennyhuo** [comment]
That will make `deepCopy` generation an implicit thing. It should be generated only if needed. 
And there is no need to perform a deep copy for vals or immutable collections.

**Comment by bennyhuo** [comment]
Maybe we could use annotations or something else to config bunch of classes to enable deep copy for them. 

```
@DeepCopyClasses
val DEEP_COPY_CLASS = listOf(A::class, B::class)

@DeepCopyPackages
val DEEP_COPY_PACKAGES = listOf("com.foo.data", ...)
```

**Comment by mustii82** [comment]
@enbandari Could be a good Solution, Any Other classes use the basic Classes of Kotlin to build up more Complex Structures, so we would be able to deepCopy them as well as they based on basic DataTypes provided by the Standard Library of Kotlin and Java

**Comment by mustii82** [comment]
> That will make `deepCopy` generation an implicit thing. It should be generated only if needed.
> And there is no need to perform a deep copy for vals or immutable collections.

Why not ? A deep Copy should always DeepCopy the whole Object with all its members.

**Comment by bennyhuo** [comment]
DeepCopy is only useful when changes will be made. This is something like the "copy on write" strategy. If types of vals or element types of immutable collections are also immutable, deep copy will make no sense but a waste of effort. 

I persist supporting deep copy on explicit declared types to avoid risking on any implicit errors and more basically I need the annotations to generate the code. 

Anyway, I'll think about how to make collections available to that. Maybe reflection can do its job. 

Pull requests are welcome.

**Comment by bennyhuo** [comment]
Now we can use this: 
```
@DeepCopyConfig(values = [Pair::class, Triple::class])
class DummyClass
```
