### ISSUE TITLE
Reference to arrays is shared between original and copied object 

### ISSUE THREAD

**Issue by NikolaDespotoski** [bennyhuo/KotlinDeepCopy#7]
```
@DeepCopy
data class ClassA(val numbers : IntArray)

```

This test fails because the objects shared same reference of the array, meaning that DeepCopy.kt passes same reference to the constructor in the `deepCopy` extension function:

```
@Test
fun testCopySharedIntArrayFails() {
    val a = ClassA(numbers= intArrayOf(1,2,3))
    val other = a.deepCopy()
    assertTrue(a.numbers.contentEquals(other.numbers))
    other.numbers[0] = 0
    assertFalse(a.numbers.contentEquals(other.numbers))
}
```

But when you use `copyOf()` to create copy of the array propery then the test passes. 

```
@Test
fun testCopySharedIntArraySuccess() {
    val a = ClassA(numbers= intArrayOf(1,2,3))
    val other = a.copy(numbers = a.numbers.copyOf())
    assertTrue(a.numbers.contentEquals(other.numbers))
    other.numbers[0] = 0
    assertFalse(a.numbers.contentEquals(other.numbers))
}
```

Generator should do `array.copyOf()` for the primitive array types when calling the constructor in the `deepCopy()` function.

**Comment by bennyhuo** [comment]
I'll check that later. Pull request is welcome.

**Comment by bennyhuo** [comment]
Builtin Arrays including Array<T>/IntArray/FloatArray etc are not supported yet. You can try Collections instead.
