### ISSUE TITLE
耗时较长问题

### ISSUE THREAD

**Issue by zh793060640** [bennyhuo/KotlinDeepCopy#8]
目前发现一些性能不好的手机，调用这个方法耗时很长，测试的场景就是，点击一个按钮去调用一个接口，调用的接口是一个data class 封装的参数，对这个对象拷贝一下，然后去网络请求，基本都是1.5秒左右响应，网络请求最多300ms

**Comment by bennyhuo** [comment]
请提供完整可复现的用例哈。

--------------原始邮件--------------
发件人："zh793060640 "<notifications@github.com&gt;;
发送时间：2020年12月18日(星期五) 下午5:07
收件人："enbandari/KotlinDeepCopy" <KotlinDeepCopy@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/KotlinDeepCopy] 耗时较长问题 (#8)
-----------------------------------

 

 
目前发现一些性能不好的手机，调用这个方法耗时很长，测试的场景就是，点击一个按钮去调用一个接口，调用的接口是一个data class 封装的参数，对这个对象拷贝一下，然后去网络请求，基本都是1.5秒左右响应，网络请求最多300ms

**Comment by bennyhuo** [comment]
是不是你的类太大了，如果方便的话还是提供一些 case 分析一下哈。我这边先关闭这个 issue，如果有需要可以重新打开。
